### ISSUE TITLE
Similarity matrix

### ISSUE THREAD

**Issue by ahangchen** [hehefan/Unsupervised-Person-Re-identification-Clustering-and-Fine-tuning#1]
Hi, I'm also implementing person re-id in keras and found this repository, but I'm confused about the similarity matrix computation in [baseline evaluation code](https://github.com/hehefan/Unsupervised-Person-Re-identification-Clustering-and-Fine-tuning/blob/master/baseline/evaluate.py#L60). 

Generally, we compute similarities between probe features and gallery features using euclidean distance formula, so the value in the similarity matrix position(i,j) will be (probe[i] - gallery[j]).^2. But in this [code](https://github.com/hehefan/Unsupervised-Person-Re-identification-Clustering-and-Fine-tuning/blob/master/baseline/evaluate.py#L60).  the value in the similarity matrix is two vectors's dot product: probe[i]*gallery[j]. 

I wonder whether this metric really works. Is there any references about this metric that compute similarity by vectors' dot product?

**Comment by ahangchen** [comment]
Got it, it's the cosine similary measure metric.

**Comment by Mickeybaby** [comment]
Hi，@ahangchen
 I want to ask you a question.
When i run 'python unsupervised.py'
FileNotFoundError: [Errno 2] No such file or directory: '../dataset/Duke/bounding_box_train/0001_c2_f0046182.jpg'
The bounding_box_train folder is not used in the dataset!
Can you give me some advice?Because the author seems to have abandoned the repo.
I'll be grateful.
Best wishes to you!

**Comment by ahangchen** [comment]
@Mickeybaby I think `bounding_box_train` is `train` directory in the dataset. You can search for 0001_c2_f0046182.jpg to confirm this.
